spring.profiles.active=local
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.datasource.url=${JDBC_DATABASE_URL\:jdbc\:postgresql\://localhost\:5432/myApp}
spring.datasource.username=${JDBC_DATABASE_USERNAME\:postgres}
spring.datasource.password=${JDBC_DATABASE_PASSWORD\:<<YOUR_PASSWORD>>}

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.file.name=logs/myApp.log

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true

error.handling.http-status-in-json-response=true
error.handling.exception-logging=NO_LOGGING
error.handling.full-stacktrace-http-statuses=5xx
error.handling.log-levels.5xx=ERROR

spring.docker.compose.lifecycle-management=start-only
springdoc.pathsToMatch=/api/**
spring.servlet.multipart.max-file-size=40MB
openapi.service.title=APIs document specification for all endpoints in Core My App
openapi.service.version=1.0.0
springdoc.swagger-ui.path=/myApp/swagger-ui.html
springdoc.api-docs.path=/myApp/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.filter=true
spring.servlet.multipart.max-request-size=40MB

application.security.jwt.secret-key=${JWT_SECRET_KEY\:your_secret_key_here}
application.security.jwt.expiration=${JWT_EXPIRATION\:expiration_time}
application.security.jwt.refresh-token.expiration=${JWT_REFRESH_EXPIRATION\:refresh_expiration_time}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email_here
spring.mail.password=your_app_password_here
application.mail.from=noreply@myApp.com

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

